### ISSUE TITLE
List index out of Range

### ISSUE THREAD

**Issue by arshah18** [mouliere-lab/FrEIA#4]
Hi Moldovan,
I am running _FrEIA_ pipeline and it is running smoothly until I run _2_FrEIA.smk_. Here is the content of the log file:

_IndexError in line 11 of /work/FrEIA/workflow/rules/2_FrEIA/2_FrEIA.smk:
list index out of range
  File "/work/FrEIA/workflow/rules/2_FrEIA/2_FrEIA.smk", line 11, in <module>_
-
_line 11: 2_FrEIA.smk
ControlGroup = ControlGroup[0][:-1]_

Could you please check this?

Thanks,
Ab,

**Comment by moldovannorbert** [comment]
Dear @arshah18 

Sorry for the very late response, I did not get a notification about your issue. Did you manage to resolve this? Because of some compatibility issues with previous versions the samplesheet.csv needs to contain two columns with headers: `sample_name` and `group`. The `group` column usually represents the phenotype of the given sample (ex. control). If you don't have this information you can replace these values with simple letters (for ex. "A"). Be aware that in it's current form FrEIA is set up to work with at least two groups (for ex. control* and cancer). Please notice the `*` next to control, which means to the tool that this group is the "control group" and is necessary for the analysis. A samplesheet.csv with a dummy group variable would look like the following:

```
sample_name group
samp1 A*
samp2 A*
samp3 A*
samp4 B
samp5 B
```

Not having a group variable will not affect your results.

**Comment by arshah18** [comment]
Thank you @moldovannorbert for the reply.
Unfortunately, I could not solve the issue and I had stop further analysis. I have added the sample sheet according to the pipeline instructions (find the attached sample sheet)
[samplesheet.csv](https://github.com/mouliere-lab/FrEIA/files/15027162/samplesheet.csv). The sample sheet columns are separated by space rather than tab or ','.
Thanks,
Ab,

**Comment by moldovannorbert** [comment]
Dear @arshah18,

Thanks for your reply. Please add a `*` next to `control` so it becomes `control*` in the `group` column and rerun the analysis when you have time.
If this resolves your issue, please close this ticket.

**Comment by jgarces02** [comment]
Hi, I'm having the exact same issue. 

This is _my samplesheet.csv_:
```
sample_name group
132663_IGO_15698_2 cancer
14783_IGO_15698_1 cancer
15883_IGO_15698_3 cancer
160023_IGO_15698_6 cancer
17465_IGO_15698_4 cancer
17701_IGO_15698_5 cancer
239823_IGO_15698_7 cancer
246242_IGO_15698_8 cancer
lib060 control*
lib061 control*
lib065 control*
lib067 control*
lib076 control*
lib080 control*
```

and _config.yaml_:
```
[...]
PanelMed: /home/garcesj/software/FrEIA/resources/FrEIApanel_medians.csv
# 11. The name of control and case samples in the metadata file.
CtrName: control*
CasName: cancer
[...]
```
(I also tried to remove the asterisk from this file, but nothing worked).

Thanks!

**Comment by jgarces02** [comment]
That's strange, now it worked... but I didn't change anything. Thanks anyway!

**Comment by moldovannorbert** [comment]
> That's strange, now it worked... but I didn't change anything. Thanks anyway!

It seems this issue is resolved. Feel free to reopen it if this bug reoccurs.
